### ISSUE TITLE
ssm-qan-api.spec missing

### ISSUE THREAD

**Issue by niall-daley** [shatteredsilicon/ssm-submodules#13]
I've taken a fresh clone of the ssm-submodules repository then attempted to build the ssm-qan-api srpm, and I get the following error:

```
$ make rpms packages=ssm-qan-api
...
+ git checkout v1.17.4
Updating files: 100% (4160/4160), done.
Previous HEAD position was 267835e Merge pull request #4 from shatteredsilicon/update-version
HEAD is now at 44dc676 Update README.md
+ sed 's/%{_version}/v1.17.4/g' ssm-qan-api.spec
sed: can't read ssm-qan-api.spec: No such file or directory
make: *** [Makefile:9: srpms] Error 2
```
I've attached the full build output: [ssm-qan-api.log](https://github.com/shatteredsilicon/ssm-submodules/files/9394477/ssm-qan-api.log)

**Comment by oblitorum** [comment]
Sorry about this, it's because I created a fix branch and re-tag the latest tag there, and the build script builds source on latest tag of `ssm-1.x` branch, which is `v1.17.4` and it's really old, it's from upstream repo, so the `ssm-qan-api.spec` is not there.

**Comment by oblitorum** [comment]
I'll inform you once that fix branch is merged
