### ISSUE TITLE
ssm-admin uninstall should clean up legacy service scripts in /etc/systemd/system

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#147]
Back in PMM days and early SSM days, the service scripts were generated at `ssm-admin add` time. We now have external config files so service scripts are static in /etc/systemd/system/.

But if the system was originally set up on old SSM and then upgraded, those old scripts in `/etc/systemd/system/ssm-*.service` can remain.

`ssm-admin uninstall` should check for them and remove them.
`rpm -e ssm-client` should also check for them and remove them.
`yum install / rpm -Uvh` should check for them and rename them to `.rpmsave`, followed by `systemctl daemon-reload`

**Comment by oblitorum** [comment]
Closed as it's completed
