### ISSUE TITLE
Add a graph showing the auto_increment usage for the max usage table

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#149]
Under MySQL / Table Statistics, at the bottom, there is a list of tables by auto_increment usage.
If we run out of auto_increment space, bad things happen.

It would be useful to have a graph showing the maximum usage of any table. If top 3 tables are, say, 80%, 70% and 60%, we want the graph line to show 80% (ignore all tables but the one with highest auto_increment depletion).

Can we add such a dashboard graph? It would make it easier to create an alert for this.

**Comment by oblitorum** [comment]
So just show a graph line of the maximum auto increment usage, when the maximum value changes, it changes, regardless of what table/column it is, right? How about this:

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/1c276795-6fd2-4916-b716-7d5d46210a17)

**Comment by gordan-bobic** [comment]
Yes, that looks good.
Will we be able to set an alert in that? I figure the table name will have to be somehow templated, and I know Grafana 5 had a problem with alerts if anything was templated.

**Comment by oblitorum** [comment]
Yeah, I think so, I tried to add an alert and make it sending notification to a slack webhook

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/67d7b39f-4997-467a-bc0b-eb323f6d8552)

the table/column name is templated, and I'm using this notification template for slack:

```
This is a custom Max Auto Increment Usage Alert
value is {{ printf "%.2f" (index .Alerts 0).Values.C }}
instance is {{ printf "%s" (index .Alerts 0).Labels.instance }}
schema is {{ printf "%s" (index .Alerts 0).Labels.schema }}
table is {{ printf "%s" (index .Alerts 0).Labels.table }}
column is {{ printf "%s" (index .Alerts 0).Labels.column}}
```

**Comment by gordan-bobic** [comment]
Great, that is exactly what we need. :-)
