### ISSUE TITLE
Add a new graph to MySQL Table Statistics Dashboard: Indexes by Fewest Rows Read

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#157]
Order ascending (the ones with fewest rows read) because we want to know which indexes aren't being used, or aren't being used enough to justify having them.

This is dependent on `userstat = 1`.
Info is retrievable via:
```
SELECT * FROM INFORMATION_SCHEMA.INDEX_STATISTICS ORDER BY ROWS_READ ASC;
```

**Comment by oblitorum** [comment]
![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/bccfcc91-021a-4a72-ab3d-664b60a1d4d8)

Added it as a table dashboard to the bottom of MySQL Table Statistics page, it shows the top 10 least used indexes, sounds good?

**Comment by oblitorum** [comment]
Should we ignore the PRIMARY index?

**Comment by gordan-bobic** [comment]
We ESPECIALLY want the PRIMARY key info. InnoDB is clustered on PK. All secondary keys point at the PK. So if the PK has had no access, that means the entire table is unused, not just indexes.

We probably want more than 10 listed, it's at the bottom so let's show 50. Additionally, we might want to add a filtering option e.g. similar to way of adding tables in QAN, let the user add / remove schemas from the view. Default should be everything except system schemas (mysql, information_schema, performance_schema).

**Comment by oblitorum** [comment]
OK, copid that

**Comment by oblitorum** [comment]
OK, managed to create a such table, just simplely added an input box to allow filtering the schemas, check if the UI/UX is acceptable:

![filter-table](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/80a50b14-6485-46ad-8131-55a5e827a31e)

Or you prefer those added filter schemas separated as different labels/buttons, and can be removed separately like those on the QAN page?

Also note that the filter key / default schemas to ignore / max rows of the table can be configured.

**Comment by gordan-bobic** [comment]
That looks great. How would I exclude schemas, e.g. system schemas (mysql, information_schema, performance_schema)?

**Comment by oblitorum** [comment]
On the dashboard edit panel:

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/961af96d-3f82-41ea-aa69-089baeca7618)

Default to "mysql,information_schema,performance_schema".

You can also change the filter key, so you can choose to filter by schema/index/table or any other key, defaults to 'schema'.
