### ISSUE TITLE
MySQL Replication page is not working properly with multiple source replication

### ISSUE THREAD

**Issue by oblitorum** [shatteredsilicon/ssm-submodules#159]
When selecting a slave host with multiple master defined on the MySQL Replication page, the dashboards on that page are not working properly. e.g.

- IO Thread Runing/SQL Thread Running showing `NO` while they are running
- MySQL Replication Delay dashboard shows only one metric

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/6f297c83-05e3-4195-8a9b-e3c26ae8c73b)

To solve this, we may need to have an additional selection drop-down for each named replication slave thread, next to the HOST drop-down.

cc @jonathanvx @gordan-bobic

**Comment by gordan-bobic** [comment]
I think an extra drop-down with each thread would be good.

But we should be able to also have the "all" default option which:
1) Shows IO / SQL threads running as No only if any of the defined threads are not running.
2) Replication error no should show the most recent error, if any threads show an error.
3) Replication lag should show one line on the graph per replication thread.
4) Binlog size / written should also be stacked graphs showing all replication threads.

Individual replication thread views should work as they do now.

**Comment by oblitorum** [comment]
Copied that

**Comment by oblitorum** [comment]
> 4. Binlog size / written should also be stacked graphs showing all replication threads.

I'm a liitle confused about this point, you mean when we're exploring the slave instance on this page, we should show all its masters' binlog graphs? In this case, the `mysqld_exporter` is running on the slave instance, it needs extra DSNs of its masters to connect to and get the binlog data with `SHOW BINARY LOGS;`.

Or you mean we show the binlog of this slave instance only, but split it into different masters, e.g. there are 2 masters, it should show 2 lines/graphs as the binlog data from each master? But is it possible to tell what data comes from which master? I checked the mariadb doc, didn't find the solution.

**Comment by gordan-bobic** [comment]
You are right, what I said made no sense. What I meant to say is not a stacked graph for binlog (there is only one binlog) but a stacked graph for relay logs. Every slave thread has its own relay log.

**Comment by oblitorum** [comment]
Ah, I see. The relay logs graphs are shown on the bottom of that page, just made them shown with all replication threads.

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/c97fb61d-d697-422f-ac64-4cf453ae440f)

**Comment by gordan-bobic** [comment]
Yes, exactly.
