### ISSUE TITLE
Add additional graph for Adaptive Hash Indexing assessment

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#163]
We currently have two graphs on `MySQL InnoDB Metrics Advanced` dashboard:
- InnoDB AHI Usage
- InnoDB AHI Maintenance

In many cases, AHI is counter-productive because it takes more work to maintain it than the benefit it provides.
We need a graph to make that assessment more obvious. The graph should show:

Left Axis:
- AHI Maintenance Operations = ( Pages Added + Pages Removed + Rows Added + Rows Removed + Rows Updated )
- AHI Hits = ( Total Searches - Misses )

Right Axis:
- Hits / Maintenance in %

( For completeness of explanation, Hits / Maintenance should be as high as possible. Value below 50% indicates that the overhead likely exceeds the performance benefits. )

**Comment by oblitorum** [comment]
Should we replace that 2 graphs with this new graph, or just append this new graph as 3th graph to that 2 graphs?

**Comment by gordan-bobic** [comment]
This new 3rd graph should be in addition to the old ones.

**Comment by oblitorum** [comment]
OK, got it.

But I have a question about the Right Axis `Hits / Maintenance in %`, I'm feeling `Hits` and `Maintenance` are in different scopes, according to this output:

```
mysql> SELECT name, comment, count FROM information_schema.innodb_metrics WHERE subsystem = 'adaptive_hash_index';
+------------------------------------------+------------------------------------------------------------------------------------+--------+
| name                                     | comment                                                                            | count  |
+------------------------------------------+------------------------------------------------------------------------------------+--------+
| adaptive_hash_searches                   | Number of successful searches using Adaptive Hash Index                            | 189768 |
| adaptive_hash_searches_btree             | Number of searches using B-tree on an index search                                 | 103568 |
| adaptive_hash_pages_added                | Number of index pages on which the Adaptive Hash Index is built                    |    402 |
| adaptive_hash_pages_removed              | Number of index pages whose corresponding Adaptive Hash Index entries were removed |      1 |
| adaptive_hash_rows_added                 | Number of Adaptive Hash Index rows added                                           |   8452 |
| adaptive_hash_rows_removed               | Number of Adaptive Hash Index rows removed                                         |      5 |
| adaptive_hash_rows_deleted_no_hash_entry | Number of rows deleted that did not have corresponding Adaptive Hash Index entries |      0 |
| adaptive_hash_rows_updated               | Number of Adaptive Hash Index rows updated                                         |      0 |
+------------------------------------------+------------------------------------------------------------------------------------+--------+
8 rows in set (0.00 sec)
```

Seems **Maintenance** is more like a counter of Adaptive Hash Index pages/rows being added/removed/updated, but **Hits** is the counter of Adaptive Hash Index being used. Doesn't this make `Hits / Maintenance` in wrong direction? Or am I misunderstanding something here?

**Comment by gordan-bobic** [comment]
That is a fair point, and yes, hits/maintenance would ideally be over 100%. 10,000% is excellent. Do you think it would be better to invert it so that low value is good? It could still easily be over 100% (but in that case a high value would be bad).

Because the scopes are, as you rightly point out, independent, it could be over 100% in either case.

**Comment by oblitorum** [comment]
Oh, OK, `Hits / Maintenance` is fine, I was just worried about that the result is not expected, but if this is expected, I'm totally fine with it.

**Comment by oblitorum** [comment]
![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/dff7d8ad-7144-463c-b0b3-70af61e4ca16)

Also, I saw the origin AHI Usage graph is using `adaptive_hash_searches` as **Misses**, but from what I understand, isn't `adaptive_hash_searches_btree` the one means **Misses**, and `adaptive_hash_searches` means **Hits**?

**Comment by gordan-bobic** [comment]
I am not 100% sure about that. I have never seen a hit ratio of more than 100%, so I think the current graph is correct, but by all means have a look if Percona's latest PMM changed it, as a cross-check.

**Comment by oblitorum** [comment]
I think they changed it in PMM v2, but in PMM v1 it still uses `adaptive_hash_searches` as **Misses**

PMM v1 -> https://github.com/percona/grafana-dashboards/blob/pmm-1.x/dashboards/MySQL_InnoDB_Metrics_Advanced.json#L2122

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/d101a4f9-c905-457d-a7cd-17a89bfb98de)

PMM v2/main -> https://github.com/percona/grafana-dashboards/blob/main/dashboards/MySQL/MySQL_InnoDB_Details.json#L18788

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/8b71dd8e-d59e-44ae-bb09-ab70aa32811d)

I think I'm gonna use `adaptive_hash_searches` as **Hits**, and `adaptive_hash_searches_btree` as **Misses**, this also match the comments in:

```
mysql> SELECT name, comment, count FROM information_schema.innodb_metrics WHERE subsystem = 'adaptive_hash_index';
+------------------------------------------+------------------------------------------------------------------------------------+--------+
| name                                     | comment                                                                            | count  |
+------------------------------------------+------------------------------------------------------------------------------------+--------+
| adaptive_hash_searches                   | Number of successful searches using Adaptive Hash Index                            | 189768 |
| adaptive_hash_searches_btree             | Number of searches using B-tree on an index search                                 | 103568 |
...
+------------------------------------------+------------------------------------------------------------------------------------+--------+
```

**Comment by gordan-bobic** [comment]
Not sure about that, the description here is rather unclear:
https://mariadb.com/kb/en/innodb-status-variables/#innodb_adaptive_hash_hash_searches

Also note that status variable names changed from MariaDB 10.5.

This article from 2016 talks about the subject but uses PMMv1 graphs:
https://www.percona.com/blog/is-adaptive-hash-index-in-innodb-right-for-my-workload/

Having said that, if Percona changed it in PMMv2, it was probably wrong, but I'm struggling to find definitive indication either way.

**Comment by gordan-bobic** [comment]
Looking at this further, between this:
https://docs.oracle.com/cd/E17952_01/mysql-em-plugin-en/myoem-metric-innodb-adaptivehashactivity-category.html

And the naming change in the MariaDB KB above,
it implies that adaptive_hash_searches_btree is misses and adaptive_hash_searches is hits.

**Comment by oblitorum** [comment]
I found a PMM bug ticket about this topic -> https://jira.percona.com/browse/PMM-943

And seems they agreed that `adaptive_hash_searches` means **Hits**, and `adaptive_hash_searches_btree/adaptive_non_hash_searches` means **Misses**.

**Comment by gordan-bobic** [comment]
OK, seems conclusive. Please fix the existing graph as well.

**Comment by oblitorum** [comment]
OK, will do

**Comment by oblitorum** [comment]
OK, another problem with `Hits / Maintenance in %` is that when the Maintenance is really small, say 0, the value of `Hits / Maintenance` will be **+∞**, the max value **Max** and **Avg** value in the legend become **+∞** too. So I set a big enough maximum value for `Hits / Maintenance` -> `100000000000.00%`, do you think that is OK?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/c28da4ac-39c9-40d4-b474-f62fde1112d5)

**Comment by oblitorum** [comment]
Or maybe **+∞** is just fine, I was thinking giving it a actual number so it looks more obvious

**Comment by gordan-bobic** [comment]
Does "auto" scale for the axis handle it sanely? Maybe override infinity to null / no data? It should only divide by 0 in the first few minutes after restart. Or override 0 into 1.

**Comment by oblitorum** [comment]
> Does "auto" scale for the axis handle it sanely? Maybe override infinity to null / no data?

I'm not sure if it should be considered as sane or not, the graph is still working, and it acts like it "overflows" the chart. The max and avg value in the legend shown as empty (or "+∞" if it's really small but not exact 0). 

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/e4687067-259f-4042-a298-ebdbf028d09b)


I guess we can override infinity to null / no data, If we decide to do that, that means there is no data to show on the chart on that period, so there might be some gaps on the chart.

> It should only divide by 0 in the first few minutes after restart. Or override 0 into 1.

Actually I'm using the rate here, so it's actually `rate(Hits) / rate(Maintenance)`, so divide by 0 could happen any time if the Maintenance doesn't change during a period of time. Or do you think we shouldn't use rate, but the actual value instead?

**Comment by gordan-bobic** [comment]
Gaps in the chart for infinity sounds good. :-)
Is rate() the delta between measurement time ticks?

What about if we combine them for a "proper" %?
```
Hits / (Hits + Maintenance)
```
That would solve the extreme ranges/0/infinity problems, would it not? And anything over 50% would mean "good".

**Comment by oblitorum** [comment]
> Is rate() the delta between measurement time ticks?

Yeah

> `Hits / (Hits + Maintenance)`

Sounds good to me, that should solve most of the extreme ranges/0/infinity cases, but on a often idle system the delta Hits and delta Maintenance could still both be 0, but that's totally acceptable as it should be I think.

**Comment by gordan-bobic** [comment]
Yes, we can't do much about that edge case. "Idle server is idle". :-)
