### ISSUE TITLE
Make mini-graphs clickable on Grafana 9 landing page

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#166]
On Grafana 5, we had the CPU, Disk I/O and Database connection mini-graphs clickable to take us to the relevant pages.
With Grafana 9, it looks like we have the CPU mini graph clickable, but the Disk I/O and DB connections mini-graphs require hovering over the top of the graph to go to the relevant dashboard with more related details.
Is there a way that functionality can be restored with Grafana 9?

**Comment by oblitorum** [comment]
Sure, if CPU mini graph can be clickable, others can be able too, I must missed something when I migrated them, will make it works
