### ISSUE TITLE
QAN Sorting: Add sorting by Latency

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#176]
The only currently available sorting order in QAN is Load / %.
It would be useful to also be able to sort by average Latency. Sometimes the most problematic queries that cause problems are very infrequent queries that take a long time to execute.

Task: Instead of always sorting by load, add sorting option (descending only) to allow switching between sorting by % load like now and average latency ms

Indexing on the QAN database may need to be enhanced to facilitate efficient sorting with this change.

**Comment by oblitorum** [comment]
Do we need to save the sorting option? If so, I think I'm gonna add this switch to the _SSM Query Analytics Settings page.

**Comment by oblitorum** [comment]
Oh, wait, it seems inconvenient, maybe just add it to the header of that QAN table, users can change it by clicking it, and we should save users' choice of sorting option, so next time they open this page, queries are sorted by the last sorting option?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/52a7bb95-6348-4818-aecc-daffe5f78a60)

**Comment by oblitorum** [comment]
Is it acceptable that we save this option at frontend?

**Comment by gordan-bobic** [comment]
No need to save it, it's OK if it always comes up with current sorting order.
Yes, I was thinking just add clickable sort option on Load and Latency.
I'm also thinking - add the sort by Count option, just for completeness while we are at it.
Always in descending order, I see no plausible reason to ever sort these in ascending order, we always want "worst" queries first.

Obviously this needs to be pushed down into the ORDER BY of the query that fetches the data.

**Comment by oblitorum** [comment]
I added this as shown like this:

![Animation](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/2036d66e-bc40-41d4-acb5-6f5692cef384)

Does this look OK?

Also the SQLs for different sorting are something like these:

sort by Load (current default sorting)
```
SELECT
		qcm.query_class_id AS query_class_id,
		COALESCE(SUM(qcm.query_count), 0) AS query_count,
		COALESCE(SUM(qcm.Query_time_sum), 0) AS query_time_sum,
		COALESCE(SUM(qcm.Query_time_sum)/SUM(qcm.query_count), 0) AS query_time_avg
                ...
	FROM query_class_metrics AS qcm
	JOIN query_classes AS qc ON qcm.query_class_id = qc.query_class_id
	WHERE qcm.instance_id = :instance_id AND (qcm.start_ts >= :begin AND qcm.start_ts < :end)
	GROUP BY qcm.query_class_id
	ORDER BY SUM(qcm.Query_time_sum) DESC
	LIMIT :limit OFFSET :offset;
```

SQLs used for sorting by Count and sorting by Latency are similar to the above one, except that the ORDER BY is different

sort by Count
```
...
	ORDER BY SUM(qcm.query_count) DESC  
...
```

sort by Latency
```
...
	ORDER BY SUM(qcm.Query_time_sum)/SUM(qcm.query_count) DESC
...
```

As you can see, those rows are aggregated, from what I understand, index won't help in this situation, is that correct? If so, We may need to change the way it saves the metric data if we want more efficient sorting.

**Comment by gordan-bobic** [comment]
Yes! That looks great, exactly what is needed.
Indexing won't help for avoiding the sorting, but an index on
```
qcm(instance_id, start_ts)
```
will help with the `WHERE` clause. We don't have it at the moment, but depending on what the other queries look like, we may be able to change the order of the PK instead. Something to review in the future when we have telemetry on the SSM database, as per https://github.com/shatteredsilicon/ssm-submodules/issues/180
