### ISSUE TITLE
Include SSM Server's Internal Database into Monitoring

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#180]
We already monitor OS level metrics as visible from inside the container SSM Server runs in.
Internal SSM MariaDB database currently does not get monitored.

This ticket is for adding the monitoring of the MariaDB database inside the container..

Make sure the database runs with:
```
innodb_monitor_enable = all
long_query_time = 0
slow_query_log = ON
slow_query_log_file = slow.log
userstat = 1
```

QAN should be configured with filtering to omit INSERT statements, since this is 99% of what QAN does and it will create a recursion problem:
- Query gets logged
- Query that gets logged gets logged
- Query that gets logged that gets logged gets logged
- ...

We may need to exclude other things as we go along and identify more things that result in runnaway logging.

This will allow us to look at optimizing internal database operation and monitor improvements we make to our custom build of MariaDB.

**Comment by oblitorum** [comment]
I feel like this is duplicate to this issue -> https://github.com/shatteredsilicon/ssm-submodules/issues/144 , is it?

Although the database config I used is:
```
[mysqld]
slow_query_log = 1
log_output = FILE
long_query_time = 0
innodb_monitor_enable = all
```

I may need to append
```
slow_query_log_file = slow.log
userstat = 1
```
to the database config

**Comment by gordan-bobic** [comment]
You are right, I think it is a duplicate.
