### ISSUE TITLE
ssm-server docker image seems to ship with many layers - they should be squashed

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#188]
It looks like the docker image we are pushing has many layers instead of just one. This should be squashed at build time. In fact, it looks like docker build flags include --squash, but it still seems to result in a multi-layered image. Ideally we want the final image to be a single flat image.

If we are dealing with a bug or limitation in docker, this should be achieved by whatever means available, even it means extracting a tarball and instantiating a flat image from that.

**Comment by oblitorum** [comment]
Hmm, seems the `--squash` argument is deprecated from recent versions, it's not listed in help message of `docker build` either. We could use [multi-stage build](https://docs.docker.com/build/building/multi-stage/) to squash instead.
Making the patch now.

**Comment by oblitorum** [comment]
Also, using `docker-slim` to shrink the image as in this [PR](https://github.com/shatteredsilicon/ssm-submodules/pull/213) also produces a single-layer image.
