### ISSUE TITLE
Monitored Instances Page Still Mentions PMM

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#191]
In the top left:
```
PMM / _SSM Monitored Instances 
```

Also, why the underscores at the beginning? Did we inherit that from PMM? Any idea why that's there?

**Comment by oblitorum** [comment]
Yeah, the underscores are inherited from PMM v1, will remove them.

Also this issue could lead to many relative things that need to be changed, e.g. the `PMM` tag name of dashboards, `pmm` keyword in the url

**Comment by gordan-bobic** [comment]
Noted. I'll make sure I test the dashboard links more thoroughly when we are nearing the release.

**Comment by gordan-bobic** [comment]
QAN reports this when there are no queries to show:
```
No data. Please check pmm-client and database configurations on selected instance.
```

I don't see a mention of this line in the PRs, can you please confirm? It should say:
```
No data. Please check ssm-client and database configurations on selected instance.
```

**Comment by oblitorum** [comment]
Yeah, I noticed that before, and fix it in this commit -> https://github.com/shatteredsilicon/qan-app/pull/32/files#diff-1bc46822a02c346298aed107a9ee699c2acd48ecf6be78301a444b1cd750bc4fL9-R9, it's merged now.

**Comment by gordan-bobic** [comment]
Great, closing.
