### ISSUE TITLE
Make qan-agent spool writing goroutine auto-restart when it crashes

### ISSUE THREAD

**Issue by oblitorum** [shatteredsilicon/ssm-submodules#207]
Currently in [qan-agent](https://github.com/shatteredsilicon/qan-agent) project, the spool writing goroutine won't auto-restart if it crashes, which lead to the qan data lost. It would be better to make it auto-restart so that the qan data harvesting can continue.

@gordan-bobic

**Comment by gordan-bobic** [comment]
Implement the auto-restart, with some additional logging. Keep this ticket open until we figure out the root cause(s) of the crash.

**Comment by oblitorum** [comment]
The root cause should be fixed with this [PR](https://github.com/shatteredsilicon/qan-agent/pull/37)
