### ISSUE TITLE
QAN: Aggregated View Across Multiple Servers

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#212]
We often have one master and many read slaves in the same replica set. Assessing QAN data server by server often produces lopsided results compared to the real picture of the cluster in aggregate.

The feature:
- Make the host selection in QAN and multiple selection tick box list.
- Show combined queries for all the hosts selected, not just one

This would effectively translate to the underlying QAN queries going from (pseudo code):
```
WHERE host = ?
```
to:
```
WHERE host IN (?list)
```

**Comment by gordan-bobic** [comment]
Bumping this to 4, again because I don't think it would be hugely difficult, and I'm getting requests for the feature. For example, where you have multiple clusters, or you have one master and many slaves where slaves are load balanced. It makes sense to look at the data in aggregate across all the slaves.

**Comment by oblitorum** [comment]
If multiple standalone servers are seletecd, do we show separate Example/Explain/TABLE for each server?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/46e0d428-ea62-4a14-a0ee-1f6e9429d3ae)

And also the 2 activity metric dashboards on the top

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/a48ed017-a862-495c-9f98-14505b837a44)

**Comment by gordan-bobic** [comment]
No, just one example per fingerprint hash - slowest one logged, same as we do for a single server.
