### ISSUE TITLE
Upstream Updates

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#215]
Please update the following in the docker image:

Rocky Linux: 9.3
Grafana: from EL9 Appstream (currently 9.2.10), we'll review if/when we need any features from newer versions
Prometheus: 2.48 (for now stick with latest due to some massive improvements since most recent LTS, until those changes make it into next LTS)
Percona Toolkit: 3.5.7
MariaDB: 10.4.32 (use my size-optimized build)
Consul: from Hashicorp: https://developer.hashicorp.com/consul/install
Orchestrator: 3.2.6 https://github.com/openark/orchestrator or remove if not necessary

**Comment by oblitorum** [comment]
Wait, we just upgraded prometheus to 2.48 because there was an [article](https://thenewstack.io/30-pull-requests-later-prometheus-memory-use-is-cut-in-half/) indicated that 2.47.2 had cut memory use in half.
Which should we choose? LTS or less memory use?

**Comment by gordan-bobic** [comment]
That is an excellent point, one that I completely forgot about.
You are right. Let's go with **Prometheus 2.48.1**, we can switch to next LTS when it comes out.

**Comment by oblitorum** [comment]
I only see MariaDB **10.4.31** in our self-hosted rpm repo, is 10.4.32 ready or should I do that?

**Comment by gordan-bobic** [comment]
@oblitorum See internal messaging for details.

**Comment by oblitorum** [comment]
@gordan-bobic Regard of `orchestrator`, turns out it's an optional feature, it's enabled when `ORCHESTRATOR_ENABLED=true` is set.
Do we need this feature? If not, we could just remove this feature and the `orchestrator` package.

**Comment by gordan-bobic** [comment]
I think we can remove Orchestrator for now. It'll be some time before we have time to work on it.
