### ISSUE TITLE
mongodb_exporter: No cluster telemetry with MongoDB 6+

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#219]
It looks like cluster telemetry dashboards are not populating. for MongoDB v6+.

**Comment by oblitorum** [comment]
Closed this as it should be fixed with PRs:
https://github.com/shatteredsilicon/qan-agent/pull/40
https://github.com/shatteredsilicon/mongodb_exporter/pull/6
