### ISSUE TITLE
Dashboard: MySQL -> InnoDB Metrics: 0 requests / 0 hits = 0% cache hit rate, should be 100% hit rate

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#220]
On the `MySQL -> InnoDB Metrics -> InnoDB Buffer Pool Requests` graph, 0 requests is show as 0 buffer pool hit rate, it should be shown as 100%.

Also, please remove the `Y-Min` for the `Right Y` axis (% hit rate).

**Comment by oblitorum** [comment]
By removing the `Y-Min` for the `Right Y` axis, you mean removing the `0` on the bottom right from the graph?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/ad5e99bf-e5d1-4999-8b4c-1ac75da1f8f2)

Or remove it from the legend on the bottom?

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/f5b6a303-ab13-4250-8177-ee798cc13153)

**Comment by gordan-bobic** [comment]
No, I mean in the Axes setup.
![zero-to-remove](https://github.com/shatteredsilicon/ssm-submodules/assets/5469306/0f156c2f-9beb-4216-b95e-87ee8825e7a7)

**Comment by oblitorum** [comment]
Unfortunately, I didn't find a easy way to remove/disable the `Y-min` in the Axes setup, I don't think Grafana offer a configuration to do that.
Although we can always do it the hard way -> create a new dashboard plugin that's similiar to this timeseries dashboard, it needs some js/css/html work to achieve that. But it feels too much for just removing/disabling the `Y-min` config.

**Comment by gordan-bobic** [comment]
I mean literally delete the "0" from the Y-Min box in the dashboards template and leave the field empty. In the same way that `Left Y` has no `Y-Max`, the `Right Y` should have an empty `Y-Min`.

**Comment by oblitorum** [comment]
Oh, got it
