### ISSUE TITLE
Query harvester toggles slow_query_log - and it shouldn't

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#226]
I noticed that if I manually set `slow_query_log=OFF`, QAN agent toggles it back to on.
It should never do this because, as I found out recently, [under certain workloads, logging slow queries can reduce performance by 60%](https://github.com/shatteredsilicon/MariaDB/issues/6).
So we should **never** automatically turn this on - it is better to lose telemetry than to cripple the performance of the server.
Instead of turning on `slow_query_log`, log a non-fatal warning if `querysource=slowlog` and `slow_query_log=OFF`.
If we manage to fix https://github.com/shatteredsilicon/MariaDB/issues/6 then maybe we can later add an exception to restore the old behaviour if and only if slow logging is no longer intensive (e.g. we if we end up with a parameter `sync_slow_log` that behaves similar to `sync_binlog`. But that is obviously some way off.

**Comment by oblitorum** [comment]
> Instead of turning on slow_query_log, log a non-fatal warning if querysource=slowlog and slow_query_log=OFF.

Currently, if the slow_query_log is OFF, there will be no query harvested, and this message will show up:

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/a0e492df-7721-42e2-9d85-103c57c187ad)

Will that do? Or we need a explicit message saying that slow_query_log should be set to ON?

**Comment by gordan-bobic** [comment]
That message is fine as it is.

What I meant in this ticket is that if I manually set it to OFF on the database, ssm-client automatically toggles it back to ON. I don't think any part of ssm-client should be changing it.

**Comment by oblitorum** [comment]
Yeah, I got that, creating the PR now
