### ISSUE TITLE
Track Total Session Memory Usage

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#230]
Add this metric to be polled and captured by mysqld_exporter:
```
SELECT SUM(memory_used) FROM information_schema.processlist;
```
This metric should be shown on the `MySQL` -> `MySQL Overview` -> `MySQL Internal Memory Overview` graph.

**Comment by oblitorum** [comment]
It seems the `memory_used` column only exists in MariaDB, not in MySQL 5.7/8.0. Anyway, I added that metric and it looks like this :

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/a49e0457-e3dc-4cb5-b4e7-034bd80dcd09)

**Comment by gordan-bobic** [comment]
Looks good.
