### ISSUE TITLE
Add "ssm-admin rename" option

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#234]
It would be really useful to be able to rename monitored servers without losing all the recorded telemetry data.

Add a feature to ssm-client to allow:
```
ssm-admin rename --client-name <new-name>
```

It should change the local configs and trigger a rename on the server side (in prometheus, qan MariaDB, consul), so that both recorded and future data gets labelled correctly.

**Comment by oblitorum** [comment]
Hmm, I just found that `ssm-admin config --client-name <new-name>` does the same trick if the server is already configured.

Should we continue adding `rename --client-name` subcommand and make it an alias? Or just stay with `config --client-name`, to keep a smaller list of commands?

**Comment by oblitorum** [comment]
Oh, except that the historical prometheus data doesn't get re-labelled after renaming currently, the historical data has `{host="<old-name>"}` label and there seems no way to change label value of historical data.

Another workaround I can think of is -> fetch the historical prometheus data and replace label value with `<new-name>`, then write it back into prometheus. After we do this to all historical prometheus data, delete the historical data.

**Comment by gordan-bobic** [comment]
Oh, that works, and propagates it up to the server? I never knew that. We don't need rename, then, no need to alias anything. I'll close this.
