### ISSUE TITLE
Fix PromQL 'Non-counter' notices on Grafana panel header

### ISSUE THREAD

**Issue by oblitorum** [shatteredsilicon/ssm-submodules#247]
Recent Prometheus/PromQL has this feature that returns a warning/notice when someone runs a `rate(...)` or `increase(...)` query with a metric name that does not end with `_total/_sum/_count`, see https://github.com/prometheus/prometheus/pull/12152

And Grafana embraces those warnings/notices, by showing them on the panel header. There is an [issue](https://github.com/grafana/grafana-prometheus-datasource/issues/159) complaining about that, which is not yet fixed.

And this causes the warnings/notices shown all over the place in SSM.

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/f4c6b2d3-3077-4798-a1ed-526357e65e36)

![image](https://github.com/shatteredsilicon/ssm-submodules/assets/61085039/cdfd1f71-75a8-4230-92d9-0e1696422647)

I reckon we need to fix that, and so far I have 2 ways to fix this:

1. Rename those metrics - Find out all the metrics that are used within `rate(...)` or `increased(...)`, and add a `_total/_sum/_count` suffix to them. There are prenty of them, like in every page.

2. Add a custom CSS to remove those notices, but this requires we to enable the Grafana setting `disable_sanitize_html`, which is not recommended as it enables XSS vulnerabilities.
```ini
[panels]
# If set to true Grafana will allow script tags in text panels. Not recommended as it enable XSS vulnerabilities.
; disable_sanitize_html = false
```

What do you think? @gordan-bobic

**Comment by gordan-bobic** [comment]
Option one seems like the only reasonable way forward. Opening things up to increased risk of XSS is not a good idea.
How intensive is renaming the metrics in prometheus if there's already several servers' worth of data in the prometheus database?

**Comment by oblitorum** [comment]
I'm thinking of doing this by adding a rename map to prometheus scrape configs, e.g.
```
mysql_global_status_innodb_data_reads -> mysql_global_status_innodb_data_reads_total
mysql_global_status_innodb_data_writes -> mysql_global_status_innodb_data_writes_total
...
```
Once the SSM gets updated, from that moment on, those metrics that get scraped into prometheus will have `_total/_sum/_count` suffix, and metrics before that moment won't have the suffix.

And then we will need to change the dashboard query to e.g. `rate({__name__=~"mysql_global_status_innodb_data_reads|mysql_global_status_innodb_data_reads_total", ...})`, so this query could work with both metrics data with or without the suffix. Actually we have done this before, after we merging the upstream of `mysqld_exporter/node_exporter...`, which changed many metric names.

This way it should be just fine, whether there's already several servers or it's a fresh setup. But note that the warnings on the panel header will still be shown if it's in a time range where those without-suffix metric data are still included. E.g. you just update SSM, and the time range is 'Last 12 hours', there are still old metric data included, so those warnings will be shown. You have to wait 12 hours to let those old data 'fade out', and those warnings will be gone.

**Comment by gordan-bobic** [comment]
Yea, temporary warnings like that we can probably live with. We just need to make sure it is mentioned in the release notes somewhere.
