### ISSUE TITLE
Build modifies files that are stored in git

### ISSUE THREAD

**Issue by niall-daley** [shatteredsilicon/ssm-submodules#25]
Running the build process as listed in README.md leaves a number of modifications to the files that are checked in. As a rule, a build should not change the source files. `git status` shows the following changes:
        modified:   build/rpmbuild-docker/dep (modified content)
        modified:   docs/fixed-vulnerabilities/rds_exporter.md
        modified:   docs/fixed-vulnerabilities/ssm-client.md
        modified:   docs/fixed-vulnerabilities/ssm-managed.md
        modified:   sources/node_exporter (modified content)
        modified:   sources/ssm-dashboards (modified content)

It looks like `docs/ ` is in .gitignore, so I'm assuming those files were added before .gitignore was updated. The best approach would be to `git rm` the files in docs/ so that git stops tracking them and behaves as expected from the .gitignore file.

The modules node_exporter and ssm-dashboards both report a selection of files being deleted, so it's probably a case of tracking down what's happening and adding them to the .gitignore for the relevant submodule, then `git rm` the files.

The module rpmbuild-docker is changing stuff in it's internal/fs/testdata/ directory, which should probaly also be .gitignored

**Comment by oblitorum** [comment]
@gordan-bobic 

`docs/` directory is for storing those fixed dependency vulnerability docs, since we forked the [ssm-doc](https://github.com/shatteredsilicon/ssm-doc/tree/1.x) repo, maybe we should move those docs to that repo?

**Comment by gordan-bobic** [comment]
Yes, OK. Put them in a separate directory.
