### ISSUE TITLE
Tuning Advisor: innodb_buffer_pool_size

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#261]
First pass approximation for this is:
```
SELECT SUM(INDEX_LENGTH)
FROM   information_schema.TABLES
WHERE  ENGINE='InnoDB';
```
rounded up to nearest GiB.

Add a warning highlighted in red if that would exceed 75% of system RAM, and instead suggest 75% of system RAM.
List in G rather than raw number.

**Comment by oblitorum** [comment]
I reckon we should also make sure the suggest value is **equal to or a multiple of innodb_buffer_pool_chunk_size * innodb_buffer_pool_instances**, so we should "rounded it up to nearest GiB that is equal to or a multiple of innodb_buffer_pool_chunk_size * innodb_buffer_pool_instances" ?

**Comment by gordan-bobic** [comment]
chunk * instances is a good call. But those won't necessarily round to a GB. So I guess we should round up or down to the nearest multiple of those and show it in biggest round unit, be it K, M, G or T.
