### ISSUE TITLE
Minimize ssm-server docker image using docker-slim

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#29]
Once we have an image based on minima EL8, see if docker-slim can be used to reduce the image further without breaking it.

**Comment by oblitorum** [comment]
Yes, I tried and it's possible to use docker-slim to reduce the image further. Managed to shrink it to about **`1.1 GB`**, but got into some small problem, trying to fix it now. 

**`1.1 GB`**  is likely to be the final size I think.

**Comment by gordan-bobic** [comment]
Great, that's a worthwhile improvement. :-)
Can you make the build process output the list of files docker-slim has removed, as a separate artefact file that we can review?
Having the package that each file belongs to would also be useful (rpm -qf /path/to/file) for cross-check.
We need to make sure that it doesn't remove something important.

**Comment by oblitorum** [comment]
Oh sorry, if we stick to the EL8 **ansible**, the size is likely goes to **`1.4 GB`** I guess.

Let me see if there is way to list those files, it's gonna to be a lot of files, docker-slim removed almost every unused files (include bin files / library files)

**Comment by oblitorum** [comment]
OK, managed to minimize the image compressed size to about **274 MB** (**1.22 GB** uncompressed) without breaking anything (or it's just that I haven't found it yet :-) ).

I think that's the best we can do with **docker-slim** now.

Removed files are logged in `logs/docker-slim-removed-files.log`, example shown below, one file per line, and the package name at the end of the line if the file is owned by any package.
```
[jason@flak ~/ssm-submodules]$ head -n 20 logs/docker-slim-removed-files.log 
/tmp/supervisord.pid
/opt/playbook-init.yml
/opt/playbook-install.yml
/var/cache/ldconfig/aux-cache: glibc-2.28-211.el8.aarch64
/var/spool/mail/grafana
/var/spool/mail/ssm
/var/spool/anacron/cron.daily: cronie-anacron-1.5.2-8.el8.aarch64
/var/spool/anacron/cron.weekly: cronie-anacron-1.5.2-8.el8.aarch64
/var/spool/anacron/cron.monthly: cronie-anacron-1.5.2-8.el8.aarch64
/home/ssm/.bashrc
/home/ssm/.bash_profile
/home/ssm/.bash_logout
/usr/include/python3.9/pyconfig-64.h: python39-libs-3.9.13-2.module_el8.7.0+3351+e02cdf9b.aarch64
/usr/include/gnumake.h: make-4.2.1-11.el8.aarch64
/usr/include/python2.7/pyconfig-64.h: python2-libs-2.7.18-11.module_el8.7.0+3331+6c5bd851.alma.aarch64
/usr/include/sys/sdt.h: systemtap-sdt-devel-4.7-1.el8.aarch64
/usr/include/sys/sdt-config.h: systemtap-sdt-devel-4.7-1.el8.aarch64
/usr/include/python3.6m/pyconfig-64.h: python3-libs-3.6.8-48.el8_7.1.alma.aarch64
/usr/share/awk/libintl.awk: gawk-4.2.1-4.el8.aarch64
/usr/share/awk/ord.awk: gawk-4.2.1-4.el8.aarch64
```

Will create a pull request if you think this is ok.

**Comment by gordan-bobic** [comment]
OK, keep this in a separate branch for .3 release merge window for now.

I take it removal of those crons won't impact log rotation in the container?

**Comment by oblitorum** [comment]
> I take it removal of those crons won't impact log rotation in the container?

Good point, I'm not very sure, let me do some tests

**Comment by oblitorum** [comment]
OK, with this [PR](https://github.com/shatteredsilicon/ssm-submodules/pull/213) it's able to shrink the compressed image to **386.85 MB** (arm64), as a comparison the .3 compressed image size is **520.42 MB**. Although the decompressed size doesn't seem to differ that much, .3 is **1.73 GB**, now is **1.61 GB**.

**Comment by gordan-bobic** [comment]
It all helps. :-)
