### ISSUE TITLE
Tuning Advisor Adjustments

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#301]
- Put up a warning at the top if there is less than 24 hours of worth of data. Or a permanent note at the top (like the one that says that if graphs are missing, to set innodb_monitor_enable=all on innodb advanced metrics dashboard) that says that the advice won't be reliable if there isn't at least 24 hours of telemetry data captured.

- innodb_log_file_size - this needs a note saying that it refers to total size of redo logs, which would be (innodb_log_file_size x innodb_log_files_in_group). Recommendation should be adjusted so that:

min: 48Mx2 (2 log files, old default) - never recommend less than this 96MB total

If at max it is <= 40% full, advise halving to next lower 2^n

If it is maxed out (fill > 90%, I think the currrent check is fill > 75%) , advise increase to next 2^n

- innodb_buffer_pool_size should be adjustable downward as well. Default is 128M, never advise less than that, but if our total InnoDB index size less than 40% of the buffer pool size, advise reducing it to the current size rounded up to the next 2^n. Or in other words, make adjustment advice work downward toward 128M minimum.

- innodb_adaptive_hash_index - this is disabled on latest version of MariaDB by default. Put a note on it that we cannot test efficiency with it disabled, and that to be able to provide advice it would need to be enabled for a period to give the advisor some data to work with.

- Connection memory usage -> "Maximum Theoretical Connection Memory Usage"
- Replication memory usage -> "Replication Memory Usage"
- Global Memory Usage => "Maximum Global Memory Usage"

**Comment by gordan-bobic** [comment]
I'm thinking that the per-thread memory usage into separate graphs.

1) Maximum Probable Connection Memory Usage - same as current block graph, minus max_allowed_packet, tmp_table_size, bulk_insert_buffer_size, read_rnd_buffer_size and read_buffer_size

2) Non-InnoDB Maximum Connection Memory Usage - bulk_insert_buffer_size, read_rnd_buffer_size and read_buffer_size  - these are MyISAM only which isn't really heavily used any more.

3) Theoretically Possible Other Connection Memory Usage - max_allowed_packet, tmp_table_size  - these are only used under specific circumstances which won't regularly materialise on most systems, and tmp_table_size isn't really limited, you can have thousands in any one session if you really want to.

And split the Theoretical Memory Usage graph and the Memory Usage Summary graphs in the same way to give a clearer overview.

**Comment by oblitorum** [comment]
> Put up a warning at the top if there is less than 24 hours of worth of data. Or a permanent note at the top (like the one that says that if graphs are missing, to set innodb_monitor_enable=all on innodb advanced metrics dashboard) that says that the advice won't be reliable if there isn't at least 24 hours of telemetry data captured.

I added a permanent note to my local depolyment, let me know if it's good enough.

![image](https://github.com/user-attachments/assets/ff2efade-57f9-4fc9-914a-b2b30e2ae2fd)

**Comment by gordan-bobic** [comment]
It would be better to word it as:
"Tuning advice on this dashboard is unlikely to be reliable until at least 24 hours of telemetry data has accumulated and you zoom out to at least 24 hours."
Also, please make it left-aligned rather than centered.

**Comment by oblitorum** [comment]
Then it should look like this

![image](https://github.com/user-attachments/assets/81ea7521-a134-43a2-b69a-009c8c308096)

**Comment by gordan-bobic** [comment]
Can you align it to top rather than bottom, or shrink the vertical size of the box?

**Comment by oblitorum** [comment]
Here is the thing, there are 2 lines, the top line is the buildin **Title** line, with a drop down switch, the bottom line is the **Body** line
![image](https://github.com/user-attachments/assets/b25c61f2-f751-43ea-91b1-07315a3a7f65)

This Grafana text panel is not very customizable, I can only align it to top and keep the **Body** line (like the one on innodb advanced metrics dashboard)
![image](https://github.com/user-attachments/assets/8cb8ae31-c626-4a9b-866a-eda5eebfd47e)

Or set it as title so we can remove the bottom **Body** line, but it will be centered
![image](https://github.com/user-attachments/assets/a38498e6-74c1-4c96-82b2-13e10abc2af2)

**Comment by gordan-bobic** [comment]
OK, centered it is then, that seems to match other similar cases on other dashboards.

**Comment by oblitorum** [comment]
> innodb_log_file_size - this needs a note saying that it refers to total size of redo logs, which would be (innodb_log_file_size x innodb_log_files_in_group).

Is this note good enough?
![image](https://github.com/user-attachments/assets/9febd74d-865d-47a3-8ba4-06a2d07db200)

> innodb_buffer_pool_size should be adjustable downward as well. Default is 128M, never advise less than that, but if our total InnoDB index size less than 40% of the buffer pool size, advise reducing it to the current size rounded up to the next 2^n. Or in other words, make adjustment advice work downward toward 128M minimum.

Note that current innodb_buffer_pool_size does advise tuning downward, the tuning rule is - always advise to the 
next multiple of `innodb_buffer_pool_chunk_size x innodb_buffer_pool_instances` of current innodb index size. e.g. `innodb_buffer_pool_chunk_size x innodb_buffer_pool_instances` is **128M**, innodb index size is **30M**, so the next mulpitle is **128M** , and current innodb_buffer_pool_size is **256M**, it will suggest downward to **128**. And if the current innodb index size is **260M**, it will suggest to next mulpitle **384M**

![image](https://github.com/user-attachments/assets/1a9b2302-2c1c-42ec-8931-4f8da2523ff6)

If we're going to change it to only advises tuning downward when index size is less than 40% of the buffer pool size, shouldn't we also suggest a value that's a multple of  `innodb_buffer_pool_chunk_size x innodb_buffer_pool_instances` ?

> innodb_adaptive_hash_index - this is disabled on latest version of MariaDB by default. Put a note on it that we cannot test efficiency with it disabled, and that to be able to provide advice it would need to be enabled for a period to give the advisor some data to work with.

Is this note good enough?
![image](https://github.com/user-attachments/assets/ddb4527c-820e-4398-acc9-772ae7bcc876)

**Comment by oblitorum** [comment]
> I'm thinking that the per-thread memory usage into separate graphs.
> - Maximum Probable Connection Memory Usage - same as current block graph, minus max_allowed_packet, tmp_table_size, bulk_insert_buffer_size, read_rnd_buffer_size and read_buffer_size
> - Non-InnoDB Maximum Connection Memory Usage - bulk_insert_buffer_size, read_rnd_buffer_size and read_buffer_size - these are MyISAM only which isn't really heavily used any more.
> - Theoretically Possible Other Connection Memory Usage - max_allowed_packet, tmp_table_size - these are only used under specific circumstances which won't regularly materialise on most systems, and tmp_table_size isn't really limited, you can have thousands in any one session if you really want to.
> 
> And split the Theoretical Memory Usage graph and the Memory Usage Summary graphs in the same way to give a clearer overview.

I adjusted locally, and it looks like this, sounds right?
![image](https://github.com/user-attachments/assets/deba3714-716f-4a28-86f6-a89e2ae5e1cb)

**Comment by gordan-bobic** [comment]
Memory graph changes look good.
Yes, we should align to chunk X instances, but - note that instances is deprecated in recent MariaDB.
I am also inclined to go up in powers of 2 because otherwise we are likely to end up in hysteresis state, that is why I proposed to propose down at under 40% and propose up at 90%, to give a 5-10% stability gap.

**Comment by oblitorum** [comment]
OK, then I'll make it go up/down in powers of 2 when it's above 90% / under 40%, and make sure the final value is aligned to a multiple of `chunk_size x instances`

**Comment by gordan-bobic** [comment]
Hmm... So next power of 2, round up to chunk x instances. And show a warning if either chunk or instances is not a power of 2, as that will upset the calculation.

Since instances is removed from 10.6, IIRC, make sure that it is assumed to be 1 if null.

**Comment by oblitorum** [comment]
> And show a warning if either chunk or instances is not a power of 2, as that will upset the calculation.

Can we just make a permanent note like this?

![image](https://github.com/user-attachments/assets/7cc130dd-14ac-4a7d-9790-e679526df5eb)


> Since instances is removed from 10.6, IIRC, make sure that it is assumed to be 1 if null.

Yeah, I made sure that.

**Comment by gordan-bobic** [comment]
I'm thinking we want a permanent warning, not a hover-over "i" warning.
But now that I think about it, we don't need it - numbers will be weird, but it should work regardless of what chunks and instances is set to. So let's just not put that warning up (if chunk or instances isn't a power of 2).

**Comment by oblitorum** [comment]
OK, got it
