### ISSUE TITLE
When upgrading from v3, prepend cpu to list of collectors in node_exporter.conf

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#307]
Upgrading from v3 results in CPU telemetry no longer collecting, because cpu is now an optional collector, and .conf files get preserved across upgrades.

Add a %post script in `.spec` to trigger when upgrading from v3 or earlier to `set` in cpu to the list of active collectors.

Also make sure the default config we ship includes the cpu collector enabled.

**Comment by oblitorum** [comment]
Maybe we should just abandon the `collectors.enabled` config, and use the separated configs (e.g. `collector.cpu`, `collector.arp` etc) instead. The `collectors.enabled` config is inherited from upstream [percona/node_exporter](https://github.com/percona/node_exporter), [prometheus/node_exporter](https://github.com/prometheus/node_exporter) doesn't have that config.

**Comment by gordan-bobic** [comment]
Yes, agreed. Making it closer to up-upstream (prometheus/node_exporter) should be a better idea in most cases.
