### ISSUE TITLE
Hostnames on the landing page are obscured by the grey triangle in the top left corner

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#308]
Can we make the hostnames vertically centered? Or right-aligned?
![ksnip_20240914-144501](https://github.com/user-attachments/assets/e4e811a6-e518-4018-83c0-9e4302a1cced)

**Comment by oblitorum** [comment]
Those hostnames were placed in the title line, and the grey triangle is also in the title line, re-placed it in the content line ->  https://github.com/shatteredsilicon/grafana-dashboards/pull/73 , so it won't be obscured by the grey triangle again, and it can be multi-line now.

![image](https://github.com/user-attachments/assets/eec75736-fe1b-4bc5-ab4b-4726910770e3)
