### ISSUE TITLE
Insights / Advisor - Tuning: I/O Threads

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#310]
With MariaDB <= 10.3, we don't seem to get any telemetry for pending reads / writes.

It should be available:
```
# mysql -e 'show engine innodb status\G' | grep -i pend
Pending normal aio reads: [0, 0, 0, 0] , aio writes: [0, 0, 0, 0] ,
Pending flushes (fsync) log: 0; buffer pool: 0
0 pending log flushes, 0 pending chkp writes
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
```

Additionally, when this is unavailable, the advisor recommends doubling the I/O threads. If this is unavailable, it should show the current value box in grey, and the advice box in grey as N/A. This information was removed in later versions, so handling it's real absence appropriately is important. But in this case, the information should be there but it isn't showing up.

**Comment by oblitorum** [comment]
I can't reproduce this with MariaDB 10.3.39, I did get telemetry for pending reads / writes on my deployment.

```
MariaDB [(none)]> select @@version;
+-----------------------------------+
| @@version                         |
+-----------------------------------+
| 10.3.39-MariaDB-0+deb10u1~bpo11+1 |
+-----------------------------------+
1 row in set (0.000 sec)
```

![image](https://github.com/user-attachments/assets/6254bc01-d171-4697-9373-305f1d3d53b6)

It uses this regex `^Pending normal aio reads:\s?(\d+)?\s(\[\d+(?:, \d+)*\])?\s?, aio writes:\s?(\d+)?\s?(\[\d+(?:, \d+)*\])?` to match the output from `show engine innodb status`, it should be able to get the pending aio reads/writes from the output you pasted I think. Maybe something else prevented it. Was the `engine_innodb_status` in mysqld_exporter.conf set to 1? Any error logged in the log file?

> Additionally, when this is unavailable, the advisor recommends doubling the I/O threads. If this is unavailable, it should show the current value box in grey, and the advice box in grey as N/A. 

Yeah, this problem does exist, will fix it, along with other tuning graphs as described in https://github.com/shatteredsilicon/ssm-submodules/issues/312

**Comment by gordan-bobic** [comment]
OK, I figured out why the pending I/O wasn't showing up - engine_innodb_status in the config wasn't enabled.
