### ISSUE TITLE
Advisor - Tuning - Algorithm Tweak

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#311]
I see a case where table_open_cache is maxed out, and set to 2000. The advisor recommends increasing to 2048, which is technically right (as it is an iterative process), but when the current value is > 90% of the recommended value, ship to the next-next power of 2.

So if current value is 2000 and maxed out, since 2000 is more than 90% of the next 2^n, the advice should be 2^n+1, i.e. 4096.

**Comment by oblitorum** [comment]
OK, adjusted the tuning algorithm here -> https://github.com/shatteredsilicon/grafana-dashboards/pull/79
Also changed the turning algorithm for `table_definition_cache`, `innodb_log_buffer_size` and `innodb_redo_log_capacity` tuning in a same way.
