### ISSUE TITLE
Advisor - Tuning: When data is unavailable in the selected period (when graphs say "no data"), the corresponding advice box should be grey and say "N/A".

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#312]
Similar to other problems when there is no data available.
When there is no data available, the recommended box should be grey and say "N/A".
Similar for InnoDB Checkpoint Age.

The box at the top of the page, in addition to saying that advice us unreliable unless there is at least 24 hours' worth of data, should also mention, like the InnoDB Advanced page, that some of the advice will be unavailable unless `innodb_monitor_enable=all` is set.

**Comment by gordan-bobic** [comment]
Found another anomaly, this should be impossible:
![impossible-advice-innodb_io_capacity](https://github.com/user-attachments/assets/20b1d678-b1d8-4a53-a96c-045be9d5b413)

innodb_io_capacity should never be advised higher than innodb_io_capacity_max.
innodb_io_capacity advised should be a % of innodb_io_capacity_max which is inferred from iops and % saturation.

**Comment by gordan-bobic** [comment]
Found another anomaly, this should be impossible:
![impossible-advice-innodb_io_capacity](https://github.com/user-attachments/assets/b33d90d1-25e7-415d-9aea-6d017a50e48b)

innodb_io_capacity should never be advised higher than innodb_io_capacity_max.
innodb_io_capacity advised should be a % of innodb_io_capacity_max which is inferred from iops and % saturation.

**Comment by gordan-bobic** [comment]
Found another anomaly, this should be impossible:
![impossible-advice-innodb_io_capacity](https://github.com/user-attachments/assets/f92ae31b-b0e9-482e-9e5e-e3e5e97c49dc)

innodb_io_capacity should never be advised higher than innodb_io_capacity_max.
innodb_io_capacity advised should be a % of innodb_io_capacity_max which is inferred from iops and % saturation.

**Comment by gordan-bobic** [comment]
And another obviously wrong advice:
![buffer-pool-advice](https://github.com/user-attachments/assets/b40994fe-22c2-4c0f-ba62-44db79e58475)

Index size: 13GB
Current buffer pool: 183GB
Advice: 183GB?? Should be 16GB

**Comment by gordan-bobic** [comment]
Why are these in yellow, they should they not be green?
![innodb_io_threads_advice](https://github.com/user-attachments/assets/3ba824de-ec09-4f05-998c-9dd493f31885)

**Comment by oblitorum** [comment]
I suspect all above issues were caused by the lack of disk/cpu/memory metrics populated from node_exporter/rds_exporter (temporary or long-term). I adjust relevant tuning dashboards to adapt this situtation, and also make those graphs grey and say “N/A" when those disk/cpu/memory metrics are missing. Hopefully that will fix it -> https://github.com/shatteredsilicon/grafana-dashboards/pull/77

**Comment by oblitorum** [comment]
> The box at the top of the page, in addition to saying that advice us unreliable unless there is at least 24 hours' worth of data, should also mention, like the InnoDB Advanced page, that some of the advice will be unavailable unless innodb_monitor_enable=all is set.

This is added like this

![image](https://github.com/user-attachments/assets/36f1609f-531a-4ab6-9040-cadf54cc1eb3)
