### ISSUE TITLE
Aurora Serverless CPU weirdness

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#314]
It isn't immediately obvious if this is an AWS side weirdness or something confusing SSM, but with Aurora Serverless v2, it looks almost like CPUs are hot-plugging and hot-unplugging. In one example I am looking at, SSM is reporting sometimes 3 vCPUs, sometimes 5 vCPUs.

Investigate where this anomaly comes from.

**Comment by gordan-bobic** [comment]
Confirmed - with Aurora Serverless elastic, both CPU and memory scale dynamically. That is why the number of CPUs and amount of memory look a little all over the place. I am not sure if we can do anything about that, or if grafana is just not able to present such elasticity in an obvious way.

**Comment by oblitorum** [comment]
I think we could show the min and max values on one graph to show the possible CPU/Memory range, when the min and max values are not the same in a period of time, e.g. 1 hour `min_over_time(rdsosmetrics_General_numVCPUs{instance=~"$host"}[1h]) != max_over_time(rdsosmetrics_General_numVCPUs{instance=~"$host"}[1h])`

![image](https://github.com/user-attachments/assets/4d84b54c-d72d-415c-af30-c7e352e05013)

**Comment by gordan-bobic** [comment]
That's not a bad idea, show it as 12-24.
And the same with RAM.

But leave all the other graphs as they are, because it is far from obvious what to do with them, and if we were to do something about them, it'd turn into endless chasing of edge cases and exceptions.

**Comment by oblitorum** [comment]
OK, added a custom panel to display this kind of range stats -> https://github.com/shatteredsilicon/grafana-dashboards/pull/80

It will look like this if the cpu/memory get scaled in past hour.

![image](https://github.com/user-attachments/assets/c6eb4232-3169-4a44-bcb0-3096a4e946db)

![image](https://github.com/user-attachments/assets/c77da52d-68c2-4824-bd85-7393579026fe)
