### ISSUE TITLE
SNMP Load Average

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#315]
It looks like the SNMP load average retriever may be wrong. I'm seeing numbers out by 10-20x. It looks like the data could be getting misinterpreted, e.g. it's actually CPU usage rather than load average.

**Comment by oblitorum** [comment]
You were right, it's mistakenly populating the CPU usage as the load average, fixed in PR -> https://github.com/shatteredsilicon/snmp_exporter/pull/9
