### ISSUE TITLE
ssm-client warning: change doc url

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#319]
Warning: The recommended upgrade process is to upgrade SSM Server first, then SSM Clients.
See Shattered Silicon's instructions for upgrading at https://github.com/shatteredsilicon/ssm-doc/blob/1.x/docs/deploy/index.md#updating

The link should be:
https://shatteredsilicon.net/software/ssm/documentation/latest/deploy/

**Comment by oblitorum** [comment]
Close as it's completed via https://github.com/shatteredsilicon/ssm-client/pull/57
