### ISSUE TITLE
RPM build seems to try to install it's own RPMS from the internet

### ISSUE THREAD

**Issue by niall-daley** [shatteredsilicon/ssm-submodules#33]
During the 'make rpms' phase, the process seems to try to try to install packages from the repository on https://dl.shatteredsilicon.net/, which causes an error if that architecture isn't already uploaded. This is visible when building on an aarch64 machine. I've attached a build log with the error.

The build should be using the RPMs it's built, rather than trying to download, possibly old, ones.

[build.log](https://github.com/shatteredsilicon/ssm-submodules/files/9634825/build.log)

**Comment by oblitorum** [comment]
@gordan-bobic 

We disscused this before and decided that this repository is used to serve those packages that can't be found in official repos or should be replaced with our version, for now only package `phantomjs` is needed in this repo, should we build it at build time instead?

**Comment by gordan-bobic** [comment]
@oblitorum I don't think we need to rebuild it with each SSM release, keep it separate.

**Comment by oblitorum** [comment]
@gordan-bobic

OK, then the problem now is that this repo doesn't support aarch64 yet, which makes the build failed on aarch64 machine. Is there anything I can do to fix this?

**Comment by gordan-bobic** [comment]
Ah, this is an excellent point. Do you have an aarch64 build for that rpm? Does it build cleanly from src.rpm?
If so, @niall-daley can you please prep the aarch64 repo, build phantomjs, sign it, and put it up there?

**Comment by oblitorum** [comment]
I just found that the older src.rpm in https://dl.shatteredsilicon.net/8/ssm/SRPMS/ won't build cleanly with `mock`. I missed one buildrequires `perl-interpreter`, I send the file on Upwork, because the file size exceed the limit here.

@niall-daley The `phantomjs` package requires another dependency `compat-openssl10-devel`, you problely should setup the dependency one first.

**Comment by gordan-bobic** [comment]
OK had a chat with @niall-daley . Here is how we think it should hang together:
- mock config should have path to a local repository owned by the mock user, e.g. /home/mock/ssm-dependencies/ or something like that. No signing or signature checking should be enabled for this specific repository.
- if phantomjs package isn't available from repositories (either local or the main one), build it, add it to the ssm-dependencies local repository, createrepo in it to created the metadata
- proceed with building everything else.

We can then sign and upload all the src.rpm and rpm files (including phantomjs) to the main repositories.

Does that make sense?

It means we avoid missing dependencies, and the whole process can complete in one go with less intervention.

**Comment by niall-daley** [comment]
To expand on that, if we have to build phantomjs, do not try to install it from a remote repository, just use the local repository. Have the first step of the build check whether the SRPM and RPM are already built in that repo path, and if not build them, and run createrepo.

Once that works reliably I can update the uploader to take the phantomjs artefacts and upload them to the pubilc repo too.

**Comment by oblitorum** [comment]
OK, sounds reasonable. Just to make sure I understand it correctly:

- When checking if phantomjs is built, only check the local repo, if not, build it.
- When building other packages which require phantomjs, enable both local and remote repos (local repo has higher priority)

Also, maybe if we found that there is update of phantomjs (only compare to local repo), we should also build it and update local repo.

**Comment by niall-daley** [comment]
Don't use the remote repo at all. Just use the local one. I presume that we're bringing phantomjs is as a git submodule? In which case we can update that as needed and check in the new version. The build should never change the source in any way. At present it leaves a lot of extra files around, but we can deal with that later.

**Comment by gordan-bobic** [comment]
Fair - and if we want to skip it and it hasn't changed, we can just manually download the rpm into the local repository. If it gets updated upstream, then we'll update that submodule accordingly independently of everything else.

**Comment by oblitorum** [comment]
OK, got it. And If we decide to use git submodule, then we need another git repo for these dependencies, for now there are `phantomjs` and `compat-openssl10`. Should we put them together in one repo, or separate into 2 repos?

**Comment by niall-daley** [comment]
If you're not using git submodules for it now, there's no need to start. Just create one repo for the prerequisites.

**Comment by oblitorum** [comment]
OK

**Comment by gordan-bobic** [comment]
We already have a repository for rpm-ing up phantomjs. It contains spec file and necessary patches.

**Comment by oblitorum** [comment]
Oh, Is it this repo https://github.com/shatteredsilicon/rpm-phantomjs ? I totally forgot, now I remember you setup this when we first met that problem. OK, then I'll use this one, should we change the name of it ?

**Comment by gordan-bobic** [comment]
Name seems appropriate, we don't want the whole upstream code base in it, just the .spec file and the necessary patches to make it build on EL8.

**Comment by oblitorum** [comment]
No, I don't mean the upstream code. I mean there is another dependency `compat-openssl10-devel` required when building phantomjs. If we put them together in one repo, maybe the name is inappropriate.

**Comment by gordan-bobic** [comment]
Ah, that rings a bell. @niall-daley what do you think? Have a ssm-builddep repo for any and all dependency rpms along these lines?

**Comment by niall-daley** [comment]
compat-openssl10-devel is a standard package in the distro supplied repo isn't it? If so we should rely on that.

**Comment by gordan-bobic** [comment]
compat-openssl10-devel doesn't seem to be on Oracle EL8 aarch64 at least.
Doesn't seem to be in CentOS EL8 either.
It is only available in some variants of EL8, and I can't actually seem to find it in any EL8 aarch64.
I think that's why we had to build our own on aarch64.
I'm afraid we'll have to bring our own. But on the plus side, we only need this for the build stage. Same with phantomjs. Neither need to feature in our release repository.

**Comment by niall-daley** [comment]
In which case we should either create a git repo for it, or ideally, use upstream's, add it as a submodule and build it if we don't have the RPM in the local repo.

**Comment by gordan-bobic** [comment]
To avoid getting bogged down in this for now, I have put the rpm packages for phantomjs here:
https://ftp.redsleeve.org/pub/misc/phantomjs/

There are separate aarch64 and x86-64 repositories, and the .src.rpm is there as well for clarity.
Can you please adjust the build process for now to get it from there for now? We can decide what exactly to do for a longer term solution later.

**Comment by oblitorum** [comment]
OK, let me create a branch for replacing the repo address, and see if the build works.
