### ISSUE TITLE
Disable Additional Telemetry With Huge Numbers of Tables

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#336]
Particularly in the context of remote monitored instances where it cannot be adjusted directly with ssm-client .conf files, if we have database servers in RDS with absurdly large number of databases and tables (this comes from working on a system with 4K schemas and 600K tables), we need additional telemetry functions disabled.

These queries are taking up way too much of server's resources:
```
SELECT EVENT_NAME,
        COUNT_STAR,
         SUM_TIMER_WAIT
FROM performance_schema.events_waits_summary_global_by_event_name
```
1.8 seconds

It runs once every 5 seconds, and in this particular case that makes it about 60% of everything the server is doing.

Various telemetry is already disabled because the number of tables is greater than 1000, but collector that triggers this query also needs to be disabled based based on the same criteria (tables > `--disable-tablestats-limit`).

**Comment by oblitorum** [comment]
Note that currently the table limit for remote monitored instances is hardcoded to 1000. Do you think we need to add an environment variable (e.g `SSM_DISABLE_TABLESTATS_LIMIT` ) for changing that limit? It might come in handy someday.

**Comment by gordan-bobic** [comment]
Yeah, that's a good idea (I presume it would still be unit16 range).
When you add it, can you also add basic info about it to `ssm-doc/docs/glossary.option.md` ?

**Comment by oblitorum** [comment]
OK, will do that
