### ISSUE TITLE
ssm-admin stop / start of an individual service seems to add phantom services

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#344]
Found on v3, so not 100% sure it is still present, but this is what I see happening:

- change `mysqld_exporter.conf`
```
ssm-admin list
```
works fine.

```
ssm-admin stop mysql:metrics
ssm-admin start mysql:metrics
ssm-admin list
We have found system services disconnected from SSM server.
Usually, this happens when data container is wiped before all monitoring services are removed or client is uninstalled.

Orphaned local services: ssm-mongodb-queries

To continue, run 'ssm-admin repair' to remove orphaned services.
```
So somehow out of nowhere ssm-mongodb-queries spuriously appeared.

**Comment by oblitorum** [comment]
I checked, and this indeed could happen in v3. And I made a fix for this before, in https://github.com/shatteredsilicon/ssm-client/pull/33/commits/a15dd38ac8d4ac05e01b001e249c1dd07de02131 . So it should be fixed in v4
