### ISSUE TITLE
EL9 Updated Grafana from 9.2.10 to 11.3 - validate that it doesn't break anything

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#345]
EL9 appstream bumped Grafana from 9.2 to 11.3.
Update our build target (if we specify Grafana version anywhere) and make sure that things don't break - including the alert auto-build.

**Comment by gordan-bobic** [comment]
On a related note - how much work would it take to provide our own Grafana 11.3 package for EL9?
There is a feature we need on one deployment that was only introduced in 11.2.

**Comment by oblitorum** [comment]
Shouldn't take long, within 1 day I hope. We planned to build our own Grafana 9.10.x before and I managed to build it, but later we decided to use Grafana 9.2.x from EL9. I guess we could just pull out those build files from git history, it should work with Grafana 11.3 too I think.

But I'm not very sure whether the grafana upgrade path 9.2 -> 11.3 is significantly difficult/buggy than 9.2 -> 10.2, I would hope they are equal.

**Comment by gordan-bobic** [comment]
It looks like Grafana provide RPMs, both for x86-64 and aarch64:
https://grafana.com/grafana/download?edition=oss&platform=arm
So let's just use their 11.3 OSS (not Enterprise) version or whatever the latest one is at build time.

The main thing is to make sure that upgrade from 9.2 to 11.3 doesn't break anything.

**Comment by oblitorum** [comment]
Oh crap, Grafana 11.3 has already removed the supports for Angular plugins:
```
...
logger=plugins.validator.angular t=2024-11-24T08:44:38.5513841Z level=error msg="Refusing to initialize plugin because it's using Angular, which has been disabled" pluginId=ssm-app
logger=plugins.validation t=2024-11-24T08:44:38.5513876Z level=error msg="Plugin validation failed" pluginId=ssm-app error="angular plugins are not supported"
logger=plugins.validator.angular t=2024-11-24T08:44:38.551409225Z level=error msg="Refusing to initialize plugin because it's using Angular, which has been disabled" pluginId=ssm-remote-instances-panel
logger=plugins.validation t=2024-11-24T08:44:38.551412016Z level=error msg="Plugin validation failed" pluginId=ssm-remote-instances-panel error="angular plugins are not supported"
logger=plugins.validator.angular t=2024-11-24T08:44:38.5514391Z level=error msg="Refusing to initialize plugin because it's using Angular, which has been disabled" pluginId=ssm-update-panel
logger=plugins.validation t=2024-11-24T08:44:38.551441975Z level=error msg="Plugin validation failed" pluginId=ssm-update-panel error="angular plugins are not supported"
...
```
Our projects [grafana-dashboards](https://github.com/shatteredsilicon/grafana-dashboards) and [qan-app](https://github.com/shatteredsilicon/qan-app) are both written in Angular. It means we will have to re-write those 2 projects in React. Another option is to investigate whether the functional code for Angular plugin is removed, if it's not removed, just disabled. Then we might be able to make a patch to re-enable it, and build our own Grafana.

I also checked the EL9 10.2.6 version, it still supports Angular plugins, although there are some UI issues need to be fixed. But it's much easier.

**Comment by gordan-bobic** [comment]
The main reason to upgrade is because we need WebEx  integration for sending out alerts. And that was added in 11.2.

Rewriting grafana-fashboards and qan-app in React sounds like way too big a task to make it into SSM 9.4.x, and I am not particularly keen on building our own custom Grafana either.

Based on this:
https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

Angular is disabled by default in Grafana 11 and will be removed in v12. For v11 it should be sufficient to set the following in grafana.ini
```
[feature_toggles]
angularDeprecationUI = false
angular_support_enabled = true
```
