### ISSUE TITLE
Alerts Folder

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#348]
It looks like the auto-generated alerts end up in Insight / SSM folder.
Can we have them in base level Alerts folder instead?

Additionally, which clicking on the alert dashboard, it seems to default to host=ssm-server, even though the alert is actually for a different host and was never auto-generated for the ssm-server host.

**Comment by oblitorum** [comment]
> Can we have them in base level Alerts folder instead?

You mean like this?

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/f7f8f6d9-0881-4b6d-915e-395582db0533">

> Additionally, which clicking on the alert dashboard, it seems to default to host=ssm-server, even though the alert is actually for a different host and was never auto-generated for the ssm-server host.

Unfortunately, it seems Grafana still doesn't support setting variables for the dashboard/panel associated to the alert rule -> https://github.com/grafana/grafana/issues/69166. It means you can only setup the dashboard/panel ID for these buttons/links, but you can't specify which host to show on that dashboard/panel.

<img width="1629" alt="image" src="https://github.com/user-attachments/assets/4fd8aae0-e374-44de-8e82-a3279d1d9e4f">


An alternative solution would be putting extra links into the alert rule annotations, like this

<img width="1672" alt="image" src="https://github.com/user-attachments/assets/a6e22ba2-49dc-4ddd-84e1-8949faac31d6">

**Comment by gordan-bobic** [comment]
Yes, I think it would be useful to have that context in the link.
