### ISSUE TITLE
Add supports for more advanced query parsing to qan-api

### ISSUE THREAD

**Issue by oblitorum** [shatteredsilicon/ssm-submodules#44]
Current version of qan-api doesn't support analysing query with temp table, which makes the **TABLES** section on the web interface not working for query with temp table.
We should add supports for more advanced parsing in next release.

![image](https://user-images.githubusercontent.com/61085039/196190010-9af7d395-1b17-4208-89db-a43655e6846e.png)

cc @gordan-bobic

**Comment by gordan-bobic** [comment]
Minor terminology nitpick - that is not strictly speaking a temp table, that is a sub-select. Internally it resolves as a temp table, of course, but a temp table would be if it was explicitly created as a temp table. :-)

**Comment by oblitorum** [comment]
Haha, OK, thanks for correcting me
