### ISSUE TITLE
Queries missing table definitions and/or explain due to not knowing what database to use

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#49]
Where the database is not currently is set or is unknown (and only Percona and MariaDB explicitly list the database in slow log metadata), we should make an extra effort to try to make this work.

If we know the tables but don't know the database, we can make an educated guess for the database to get the table definition and explain in:

```
SELECT table_schema information_schema.tables WHERE table_name=@name_of_tables ORDER BY table_rows DESC LIMIT 1;
```

It would help get table definition plans in most cases where we currently don't get it.

**Comment by oblitorum** [comment]
- Is this a one-time guess or it should be run every time we try to get the definition/explain?
- Maybe add a label to the EXPLAIN/TABLES section on the web page, indicate that the database of that SQL is guessed?

**Comment by gordan-bobic** [comment]
- It should probably be guessed whenever we don't know it for sure.
- If the guess is not ambiguous (there is only one database containing all of the mentioned tables), we don't need to mention the database is guessed. Otherwise, yes, if it could be ambiguous, we should add a comment that the database schema was guessed because it wasn't in the slow log.

Note that if extended slow log metadata is present (log_slow_verbosity = query_plan,explain on MariaDB, can't remember what it is on Percona off the top of my head), the explain is actually encoded in comments in the slow log, so we don't need to run explain on the query - when this is present, it should come directly from the slow log, as that was accurate at the time when the query was run.

Getting it from the extended metadata slow log (when available, obviously) also has the added advantage that this will provide an explain plan in the edge case where an explicitly created temporary table is used in the query that won't exist later if the ssm agent has to explain it itself.

I'm pretty sure the explain plan already defaults to being fetched from the slow log when available.

**Comment by oblitorum** [comment]
OK, got it

**Comment by oblitorum** [comment]
Do you think it's a good idea to add the comment like this?

![CleanShot 2022-12-07 at 00 41 18@2x](https://user-images.githubusercontent.com/61085039/205971160-1f3ca379-7890-455c-95ca-befc314b3fac.png)

**Comment by gordan-bobic** [comment]
I'm thinking
s/the database of this table is/table schema/
being super-concise is a good thing, in my experience. :-)

Also please put the text "(table schema is guessed)" to make it more obvious.

**Comment by oblitorum** [comment]
OK, will replace it with `(table schema is guessed)`
