### ISSUE TITLE
Move server image scanning to the end and parallelize the scan

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#51]
I think the scanning should be changed as follows:

1) Move the scanning to the end, just before the completed image is uploaded to dockerhub

2) Parallelize the scan, i.e. instead of:
```
clamscan -ir /some/path
```
we should do
```
find /some/path -type f -print0 | xargs -0 -n1 -P$(nproc) clamdscan --multiscan --fdpass --quiet
```

clamd is now running on all the build hosts, so the latter should work. The speed-up seems proportional to the number of cores in the server.

**Comment by oblitorum** [comment]
Closed by #58
