### ISSUE TITLE
Put together ssm-client .deb package

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#53]
We are going to need this. A lot of people use .deb based distros.
Extra bonus points if we can put together a distro and version agnostic package, i.e. a single .deb package that will install on Ubuntu 18.04+ and Debian 8+ (all LTS versions that are not yet EOL).

We need 8.6.1.17.5.1 version of this (hence tagged milestone 1), signed and with a repo or whatever .deb way of handling repos is.

**Comment by oblitorum** [comment]
@niall-daley 

I'm planning to setup another script (e.g. `make debs`) to build deb packages, and the artefacts will go to `results/DEBS/`. Does it sound ok?

**Comment by gordan-bobic** [comment]
Sounds good to me. @niall-daley ?

**Comment by niall-daley** [comment]
Assuming that it builds them in a docker container so we don't have to find more build servers, that sounds like a good plan.
