### ISSUE TITLE
Adjust SSM-server MariaDB config (00-ssm.cnf)

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#55]
Remove:
```
innodb_flush_method = O_DIRECT
```
Default (fsync) is better fro making generic use of OS cache for unpredictable sizes of database where thee needed memory for caching can vastly exceed the innodb_buffer_pool_size (defaults to 128MB).

Add:
```
innodb_buffer_pool_dump_at_shutdown = OFF
innodb_buffer_pool_load_at_startup = OFF
innodb_compression_algorithm = lz4
innodb_flush_neighbors = 0
innodb_page_size = 64K
```

`innodb_page_size` has to be set in the config before the database directory is initialised.

By default, enable page compression on the `ssm.query_class_metrics` table. Create with with `PAGE_COMPRESSED=1` in the  table definition.

PMM and SSM work so much better with docker directory on ZFS with default 128KB file system block size and lz4 compression (which is super-cheap), so without ZFS, we have to do the compression ourselves.

We need to make defaults optimal for non-ZFS (enable page compression) but add a SSM docker container environment startup variable called `ZFS=[0|1]` so that MariaDB level compression can be disabled (if it is enabled in table definition) if we are on ZFS that does more effective compression.

If `ZFS=1` and size of query_class_metrics table is < 1GB (you can get size from information_schema.tables.data_length) and definition says `PAGE_COMPRESSED=1`.
```
ALTER TABLE ssm.query_class_metrics PAGE_COMPRESSED=0;
```
Also, if ZFS=1, we should omit
```
innodb_flush_log_at_trx_commit = 2
```
from the config because if ZFS is an option it is better (faster and safer) to set `sync=disabled` at ZFS level.

**Comment by oblitorum** [comment]
> If ZFS=1 and size of query_class_metrics table is < 1GB (you can get size from information_schema.tables.data_length) and definition says PAGE_COMPRESSED=1.
> ```ALTER TABLE ssm.query_class_metrics PAGE_COMPRESSED=0;```

@gordan-bobic As the data grows, if it exceeds 1GB at some point, should PAGE_COMPRESSED be enabled again? If so, it should check the data length of `ssm.query_class_metrics` everytime some data got inserted into the table.

**Comment by gordan-bobic** [comment]
@oblitorum no, the reason for the 1GB size limit is because we don't want to end up in the situation where a huge table ends up being rebuilt just because we toggled the option. If the data size is over 1GB, we don't rebuild it in either direction because it would take far too long.

Ideally everybody would run it on ZFS, and we'll document that as the optimal way for a large database. But I expect most deployments made by other people won't be on ZFS even if all of the ones we deploy for clients will be.

**Comment by oblitorum** [comment]
Oh, I got it. Then it should check the PAGE_COMPRESSED at container startup time.

**Comment by oblitorum** [comment]
And the way I choose to determine if it is on ZFS -> `"$(stat -L -f -c \"%T\" /var/lib/mysql)" == "zfs"`, in case someone doesn't choose to run docker on ZFS, but binds the mysql/mariadb data directory to a ZFS pool instead. Does it sounds right?

**Comment by gordan-bobic** [comment]
That is a great idea. I hadn't thought of that! :-)
In that case, forget about the parameter passed to the docker image, we don't need it. Just make it automatically "do the right thing" based on the file system it detects.
