### ISSUE TITLE
Add support for showing stored procedures in QAN

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#65]
There are currently no details shown when the SQL is a CALL to a stored procedure.
For these, we should show the output of `SHOW CREATE PROCEDURE` in QAN.

**Comment by oblitorum** [comment]
I checked the source code, I believe the detail of other types such as stored function, view and etc are not showing either, should we add support for those types too? It's pretty much the same as adding support for stored procedures.

Also, should we put the detail of stored procedures under the **TABLES** section on web interface, or create a new section called **PROCEDURES** and put them there?
![CleanShot 2022-11-30 at 19 52 25@2x](https://user-images.githubusercontent.com/61085039/204789511-61346c8c-28d4-4cd6-96f3-2aed5588e84b.png)

I think adding a new section is more appropriate

**Comment by gordan-bobic** [comment]
Definitely a new section, or for stored procedures replace TABLES with PROCEDURE.

I wanted to say PROCEDURES or in addition to TABLES, but then we also have to implement a very advanced SQL parser that can pick out additional procedures called, recursively, along with all the tables from them - and that can turn into a recursion mess very easily, so I think we should stay well away from it.

Just having the procedure code shown would be a huge improvement on having nothing at all, so let's just go with that.

VIEWs, yes, we should show those in a similar way, with the VIEW definition.

Functions - I don't think we want to do this because functions are called from queries, so SELECT function(something) would also involve more advanced query parsing which I am not sure we want to do quite yet. Anything that involves advanced query parsing is going to be a separate project that will probably be worked on across several release cycles before being merged.

**Comment by oblitorum** [comment]
OK, I get your point.

And noted that we don't implement the SQL parser by ourself currently, we use the parser from [this project](https://github.com/vitessio/vitess), which seems to be a core component of YouTube.

**Comment by gordan-bobic** [comment]
Oh, cool, I hadn't realised where it come from.
