### ISSUE TITLE
Modify node_exporter and mysqld_exporter to get access credentials from a config file

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#69]
When ssm-admin config/add runs, it hard-codes some things into the service script it builds.

1. Modify node_exporter and mysqld_exporter to use a config file, if they don't have such functionality already
2. Make ssm-admin generate the config file without relying on making custom systemd service scripts for the services
3. Config files should go somewhere appropriate under /opt/ss/. Make sure the config files are created with minimum necessary privileges.
4. Make systemd service scripts static and part of the package, they should go to the systemd service script directory (on RHEL derived distros that is /lib/systemd/system)

This makes our service scripts static and it means we can replace them on upgrade with any fixes and improvements we come up with.

**Comment by oblitorum** [comment]
Closed via https://github.com/shatteredsilicon/ssm-submodules/pull/72
