### ISSUE TITLE
"Total Size of InnoDB Log Files" missing on "InnoDB Log File Usage Hourly" Graph

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#76]
it looks like on recent MariaDB (10.5+), we don't get the "Total Size of InnoDB Log Files" red line on the "InnoDB Log File Usage Hourly" graph.
I am not 100% sure, but I suspect it could be because in recent MariaDB there is only one InnoDB log file rather than multiple log files. That could be upsetting the calculation.

Please adjust the graph calculation so it works with both old (<= 10.4) and new (>= 10.5) versions.

**Comment by oblitorum** [comment]
You're probably right, the graph uses `innodb_log_files_in_group * innodb_log_file_size` to calculate the value, and the `innodb_log_files_in_group` global variable is ablout to be removed in 10.6, it's still there in 10.5.19, so the graph should work with (<= 10.5.19) I think, maybe they removed it in (>= 10.5.20)

<img width="933" alt="CleanShot 2023-02-07 at 23 12 23@2x" src="https://user-images.githubusercontent.com/61085039/217284931-57b6fdab-c3e8-40c6-9121-ba20c18169e8.png">

**Comment by oblitorum** [comment]
Wait, it seems that 10.5.19 is the latest version of 10.5, and the graph is working, are you sure it's not 10.6 we are talking about?

<img width="787" alt="CleanShot 2023-02-07 at 23 45 34@2x" src="https://user-images.githubusercontent.com/61085039/217292744-2e20cf6f-a8f7-4108-bde7-a007af3b4981.png">

**Comment by gordan-bobic** [comment]
10.7.x is definitely manifesting the problem, try with that.
