### ISSUE TITLE
Remaining PMM References in Query Analytics

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#82]
When there are no queries to be displayed in Query Analytics, the notification message still shows references to PMM.
```
There is no query data because the MySQL Server is not configured for monitoring. For details about the required configuration, see Configuring MySQL for Percona Monitoring and Management in PMM documentation.
```

**Comment by oblitorum** [comment]
Seems we already have those docs ready in [this pr](https://github.com/shatteredsilicon/ssm-doc/pull/1/commits/68149c8f138c06e7930751467db999e66ab72a8b) of [ssm-doc](https://github.com/shatteredsilicon/ssm-doc) repo.

Should we just reference to the github repo for now? Like what I did in this [commit](https://github.com/shatteredsilicon/qan-app/commit/3cb9ca05c7fbf5626bb278ce12b24c9763c9d199)

**Comment by gordan-bobic** [comment]
I'm talking about this part of that error message:
```
Percona Monitoring and Management in PMM documentation
```

That should say:
```
Shattered Silicon Monitoring in SSM documentation
```

**Comment by oblitorum** [comment]
You mean just change the title? Shouldn't we change the link also?

![CleanShot 2023-02-24 at 03 43 32@2x](https://user-images.githubusercontent.com/61085039/221013521-3349a17f-2d02-4751-b57e-192a3860584a.png)

**Comment by gordan-bobic** [comment]
We should change both.

**Comment by oblitorum** [comment]
OK, so it's ok to link it to [ssm-doc](https://github.com/shatteredsilicon/ssm-doc) repo for now, right?

**Comment by gordan-bobic** [comment]
Yes it is.
