### ISSUE TITLE
Quoted table and column names get parameterised, and they shouldn't

### ISSUE THREAD

**Issue by gordan-bobic** [shatteredsilicon/ssm-submodules#84]
Things break when they get parameterised.

For example:

```
SELECT "expire", "value" FROM "semaphore" WHERE "name" = 'router_rebuild';
```

That will come up in QAN as:

```
SELECT ?,
        ?
FROM ?
WHERE ? = ?
```

It will then also fail to identify tables used or provide an explain plan.
It's stupid, but some frameworks seem to do this kind of insane, broken over-quoting. When they quote, they should use backticks for column and table names, but it is what it is, and unfortunately, MariaDB lets them get away with it, so we have to find a way to make this work.

**Comment by oblitorum** [comment]
I did some tests (result at the bottom), and these are my  conclusions:
1. I don't think mariadb allow quoted table name (at least it's not allowed in 10.6.12), that's probably a failed SQL, but we can still fix the table name though.
2. And mariadb doesn't allow quoted column name in WHERE clause either I think, it treat it as a string instead, so `WHERE "name" = 'router_rebuild'` will be 'a string compare to another string'. I'm not very sure if we should fix the quoted column name, because we don't know if it's a column name or a plain string, unless we go through the columns of table and check if it's there, but this sounds problematic to me.

```sql
MariaDB [test]> SELECT @@version;
+---------------------+
| @@version           |
+---------------------+
| 10.6.12-MariaDB-log |
+---------------------+
1 row in set (0.001 sec)

MariaDB [test]> SELECT * FROM t;
+------+
| c    |
+------+
| A    |
+------+
1 row in set (0.001 sec)

MariaDB [test]> SELECT "c" FROM "t" WHERE "c" = 'A';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"t" WHERE "c" = 'A'' at line 1
MariaDB [test]> SELECT "c" FROM t WHERE "c" = 'A';
Empty set (0.000 sec)

MariaDB [test]> SELECT "c" FROM t WHERE "c" = 'c';
+---+
| c |
+---+
| c |
+---+
1 row in set (0.000 sec)

MariaDB [test]> 
```

**Comment by gordan-bobic** [comment]
Try with sql_mode set to empty:
```
sql_mode=''
```

The server I'm seeing it on is MariaDB 10.3.x.
The example I gave is a literal paste from the slow log.

I am not sure what transpires, but whatever Drupal emits ends up in the log this way. I have never seen it before, but the fact I am seeing it right now means that it must be possible.

**Comment by oblitorum** [comment]
I think failed SQLs also go to slow log file:

```sql
MariaDB [(none)]> xxx;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'xxx' at line 1
MariaDB [(none)]> exit
Bye
[jason@flak ~]$ sudo cat /var/lib/mysql/slow.log | grep "xxx"
xxx;
[jason@flak ~]$
```

**Comment by oblitorum** [comment]
Regardless of it's a failed SQL or not, we can fix the quoted table name anyway. 
But I think there is a problem about fixing the quoted column name, because we can't be sure whether it's a column name or it's just a plain string, not even if the quoted string matches a column name in the table

**Comment by gordan-bobic** [comment]
I did just ask the owner of the system where I found this to make sure their code actually works because you are right, that literally shouldn't work. But it seems to.

**Comment by oblitorum** [comment]
OK, I'm ok whether it's a vaild SQL or not, we can fix the quoted table name anyway.
But what about the "quoted column name", take `WHERE "name" = 'router_rebuild';` as an example, we can't just remove the double quote and say it's a column, what if user just want to use it as 'a string compare to another string'.

**Comment by oblitorum** [comment]
I still don't believe mariadb/mysql will allow "quoted column name", if so, how does mariadb/mysql tell whether `WHERE "name" = 'router_rebuild';` is "WHERE COLUMN = STRING" or "WHERE STRING = STRING", that is ambiguous.

**Comment by gordan-bobic** [comment]
Yes, I agree - I can't figure out how this can possibly be working. So I am not sure what the sane solution might be to a problem that clearly isn't sane.

Let's put this on hold for now, let's see of there is anything I can figure out from the other side.
